### ISSUE TITLE
Acoustic Echo Cancellation ( Echoey audio) during the call 

### ISSUE THREAD

**Issue by tongwu226** [CultureHub/LiveLab#2]
In an earlier version of LiveLab that uses the web audio API with media streams, echo cancellation wasn't applied properly, which causes audio of each stream to be rendered twice and created annoying echo.  

This seems to be a bug with WebRTC handling audio processing functions. There's a reported issue addressing the not functioning of AEC when using web audio API: 
[Issue 687574: AEC when using Web Audio API](https://bugs.chromium.org/p/chromium/issues/detail?id=687574)

**Comment by tongwu226** [comment]
Updated: Currently we cannot fix the echoey audio bug, so we stop using web audio API for the public release version.

**Comment by ojack** [comment]
Closing this because it is fixed, but feel free to continue discussion.
