### ISSUE TITLE
Common Issue: camera or mic access permission not show on page load 

### ISSUE THREAD

**Issue by tongwu226** [CultureHub/LiveLab#3]
When you use Livelab, or any of its testing versions, for the first time, the Chrome browser should pop up windows right underneath the address bar on the initiation page to ask for access permission to your devices' camera and mic: 

![Screen Shot 2020-05-26 at 7 30 36 PM](https://user-images.githubusercontent.com/21051323/82960223-d9b2da80-9f87-11ea-92f5-8094c57a0669.png)
![Screen Shot 2020-05-26 at 7 30 48 PM](https://user-images.githubusercontent.com/21051323/82960224-da4b7100-9f87-11ea-8369-7e0a37bc5c8c.png)

Once you **click "Allow" for both,** your audio and video feeds should be loaded, and you should see your video feed in the background. 

Then you should **refresh the whole page** to activate the function to read all of your input devices (default webcam, external webcam, camTwist, etc.) 

--- 

**Common Issues:** 
There are cases when the browser doesn't pop up options to allow mic&camera, and in the console you could find errors as following: 
![Screen Shot 2020-05-26 at 8 04 13 PM](https://user-images.githubusercontent.com/21051323/82961701-213b6580-9f8c-11ea-9467-60b950e793dc.png)

![Screen Shot 2020-05-26 at 8 06 36 PM](https://user-images.githubusercontent.com/21051323/82961822-74151d00-9f8c-11ea-92cd-1e6ca1581bfc.png)

You then will need to reset your browser permissions. 

**Steps to reset Chrome permissions for LiveLab**

1. Click the lock icon next to address bar 
2. Open **Site Settings**

![Screen Shot 2020-05-26 at 8 22 17 PM](https://user-images.githubusercontent.com/21051323/82962675-da9b3a80-9f8e-11ea-927a-e1c9ac0e0e6b.png)

3. Under Permissions, set "Camera" and "Microphone" to  "Allow"
 
![Screen Shot 2020-05-26 at 8 29 17 PM](https://user-images.githubusercontent.com/21051323/82962932-98bec400-9f8f-11ea-8adc-b11009e0f5d4.png)

4. Come back to the Livelab initation page, and reload the page. You should see both your audio and video feeds are loaded now.

**Comment by ojack** [comment]
@tongwu226 is this fixed now?

**Comment by tongwu226** [comment]
Yes! Fixed!
